// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package auth_service

import (
	"context"
	"messenger/internal/core/auth"
	"messenger/internal/core/domain"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockUsersRepository creates a new instance of MockUsersRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUsersRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUsersRepository {
	mock := &MockUsersRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUsersRepository is an autogenerated mock type for the UsersRepository type
type MockUsersRepository struct {
	mock.Mock
}

type MockUsersRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUsersRepository) EXPECT() *MockUsersRepository_Expecter {
	return &MockUsersRepository_Expecter{mock: &_m.Mock}
}

// CreateUser provides a mock function for the type MockUsersRepository
func (_mock *MockUsersRepository) CreateUser(ctx context.Context, user domain.User) (domain.User, error) {
	ret := _mock.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.User) (domain.User, error)); ok {
		return returnFunc(ctx, user)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.User) domain.User); ok {
		r0 = returnFunc(ctx, user)
	} else {
		r0 = ret.Get(0).(domain.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.User) error); ok {
		r1 = returnFunc(ctx, user)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUsersRepository_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type MockUsersRepository_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - user domain.User
func (_e *MockUsersRepository_Expecter) CreateUser(ctx any, user any) *MockUsersRepository_CreateUser_Call {
	return &MockUsersRepository_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, user)}
}

func (_c *MockUsersRepository_CreateUser_Call) Run(run func(ctx context.Context, user domain.User)) *MockUsersRepository_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.User
		if args[1] != nil {
			arg1 = args[1].(domain.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUsersRepository_CreateUser_Call) Return(user1 domain.User, err error) *MockUsersRepository_CreateUser_Call {
	_c.Call.Return(user1, err)
	return _c
}

func (_c *MockUsersRepository_CreateUser_Call) RunAndReturn(run func(ctx context.Context, user domain.User) (domain.User, error)) *MockUsersRepository_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetUser provides a mock function for the type MockUsersRepository
func (_mock *MockUsersRepository) GetUser(ctx context.Context, id uuid.UUID) (domain.User, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetUser")
	}

	var r0 domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (domain.User, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) domain.User); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUsersRepository_GetUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUser'
type MockUsersRepository_GetUser_Call struct {
	*mock.Call
}

// GetUser is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockUsersRepository_Expecter) GetUser(ctx any, id any) *MockUsersRepository_GetUser_Call {
	return &MockUsersRepository_GetUser_Call{Call: _e.mock.On("GetUser", ctx, id)}
}

func (_c *MockUsersRepository_GetUser_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockUsersRepository_GetUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUsersRepository_GetUser_Call) Return(user domain.User, err error) *MockUsersRepository_GetUser_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUsersRepository_GetUser_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (domain.User, error)) *MockUsersRepository_GetUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByUsername provides a mock function for the type MockUsersRepository
func (_mock *MockUsersRepository) GetUserByUsername(ctx context.Context, username string) (domain.User, error) {
	ret := _mock.Called(ctx, username)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByUsername")
	}

	var r0 domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (domain.User, error)); ok {
		return returnFunc(ctx, username)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) domain.User); ok {
		r0 = returnFunc(ctx, username)
	} else {
		r0 = ret.Get(0).(domain.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, username)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUsersRepository_GetUserByUsername_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByUsername'
type MockUsersRepository_GetUserByUsername_Call struct {
	*mock.Call
}

// GetUserByUsername is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
func (_e *MockUsersRepository_Expecter) GetUserByUsername(ctx any, username any) *MockUsersRepository_GetUserByUsername_Call {
	return &MockUsersRepository_GetUserByUsername_Call{Call: _e.mock.On("GetUserByUsername", ctx, username)}
}

func (_c *MockUsersRepository_GetUserByUsername_Call) Run(run func(ctx context.Context, username string)) *MockUsersRepository_GetUserByUsername_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUsersRepository_GetUserByUsername_Call) Return(user domain.User, err error) *MockUsersRepository_GetUserByUsername_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUsersRepository_GetUserByUsername_Call) RunAndReturn(run func(ctx context.Context, username string) (domain.User, error)) *MockUsersRepository_GetUserByUsername_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockHasher creates a new instance of MockHasher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHasher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHasher {
	mock := &MockHasher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockHasher is an autogenerated mock type for the Hasher type
type MockHasher struct {
	mock.Mock
}

type MockHasher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHasher) EXPECT() *MockHasher_Expecter {
	return &MockHasher_Expecter{mock: &_m.Mock}
}

// Compare provides a mock function for the type MockHasher
func (_mock *MockHasher) Compare(hash string, password string) error {
	ret := _mock.Called(hash, password)

	if len(ret) == 0 {
		panic("no return value specified for Compare")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = returnFunc(hash, password)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockHasher_Compare_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Compare'
type MockHasher_Compare_Call struct {
	*mock.Call
}

// Compare is a helper method to define mock.On call
//   - hash string
//   - password string
func (_e *MockHasher_Expecter) Compare(hash any, password any) *MockHasher_Compare_Call {
	return &MockHasher_Compare_Call{Call: _e.mock.On("Compare", hash, password)}
}

func (_c *MockHasher_Compare_Call) Run(run func(hash string, password string)) *MockHasher_Compare_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockHasher_Compare_Call) Return(err error) *MockHasher_Compare_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockHasher_Compare_Call) RunAndReturn(run func(hash string, password string) error) *MockHasher_Compare_Call {
	_c.Call.Return(run)
	return _c
}

// Hash provides a mock function for the type MockHasher
func (_mock *MockHasher) Hash(password string) (string, error) {
	ret := _mock.Called(password)

	if len(ret) == 0 {
		panic("no return value specified for Hash")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (string, error)); ok {
		return returnFunc(password)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(password)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(password)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHasher_Hash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Hash'
type MockHasher_Hash_Call struct {
	*mock.Call
}

// Hash is a helper method to define mock.On call
//   - password string
func (_e *MockHasher_Expecter) Hash(password any) *MockHasher_Hash_Call {
	return &MockHasher_Hash_Call{Call: _e.mock.On("Hash", password)}
}

func (_c *MockHasher_Hash_Call) Run(run func(password string)) *MockHasher_Hash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockHasher_Hash_Call) Return(s string, err error) *MockHasher_Hash_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockHasher_Hash_Call) RunAndReturn(run func(password string) (string, error)) *MockHasher_Hash_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTokenProvider creates a new instance of MockTokenProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTokenProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTokenProvider {
	mock := &MockTokenProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTokenProvider is an autogenerated mock type for the TokenProvider type
type MockTokenProvider struct {
	mock.Mock
}

type MockTokenProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTokenProvider) EXPECT() *MockTokenProvider_Expecter {
	return &MockTokenProvider_Expecter{mock: &_m.Mock}
}

// GenerateTokenPair provides a mock function for the type MockTokenProvider
func (_mock *MockTokenProvider) GenerateTokenPair(userID uuid.UUID, tokenID uuid.UUID) (auth.TokenPair, error) {
	ret := _mock.Called(userID, tokenID)

	if len(ret) == 0 {
		panic("no return value specified for GenerateTokenPair")
	}

	var r0 auth.TokenPair
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID, uuid.UUID) (auth.TokenPair, error)); ok {
		return returnFunc(userID, tokenID)
	}
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID, uuid.UUID) auth.TokenPair); ok {
		r0 = returnFunc(userID, tokenID)
	} else {
		r0 = ret.Get(0).(auth.TokenPair)
	}
	if returnFunc, ok := ret.Get(1).(func(uuid.UUID, uuid.UUID) error); ok {
		r1 = returnFunc(userID, tokenID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTokenProvider_GenerateTokenPair_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateTokenPair'
type MockTokenProvider_GenerateTokenPair_Call struct {
	*mock.Call
}

// GenerateTokenPair is a helper method to define mock.On call
//   - userID uuid.UUID
//   - tokenID uuid.UUID
func (_e *MockTokenProvider_Expecter) GenerateTokenPair(userID any, tokenID any) *MockTokenProvider_GenerateTokenPair_Call {
	return &MockTokenProvider_GenerateTokenPair_Call{Call: _e.mock.On("GenerateTokenPair", userID, tokenID)}
}

func (_c *MockTokenProvider_GenerateTokenPair_Call) Run(run func(userID uuid.UUID, tokenID uuid.UUID)) *MockTokenProvider_GenerateTokenPair_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTokenProvider_GenerateTokenPair_Call) Return(tokenPair auth.TokenPair, err error) *MockTokenProvider_GenerateTokenPair_Call {
	_c.Call.Return(tokenPair, err)
	return _c
}

func (_c *MockTokenProvider_GenerateTokenPair_Call) RunAndReturn(run func(userID uuid.UUID, tokenID uuid.UUID) (auth.TokenPair, error)) *MockTokenProvider_GenerateTokenPair_Call {
	_c.Call.Return(run)
	return _c
}

// ParseAccessToken provides a mock function for the type MockTokenProvider
func (_mock *MockTokenProvider) ParseAccessToken(token string) (uuid.UUID, error) {
	ret := _mock.Called(token)

	if len(ret) == 0 {
		panic("no return value specified for ParseAccessToken")
	}

	var r0 uuid.UUID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (uuid.UUID, error)); ok {
		return returnFunc(token)
	}
	if returnFunc, ok := ret.Get(0).(func(string) uuid.UUID); ok {
		r0 = returnFunc(token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(token)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTokenProvider_ParseAccessToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ParseAccessToken'
type MockTokenProvider_ParseAccessToken_Call struct {
	*mock.Call
}

// ParseAccessToken is a helper method to define mock.On call
//   - token string
func (_e *MockTokenProvider_Expecter) ParseAccessToken(token any) *MockTokenProvider_ParseAccessToken_Call {
	return &MockTokenProvider_ParseAccessToken_Call{Call: _e.mock.On("ParseAccessToken", token)}
}

func (_c *MockTokenProvider_ParseAccessToken_Call) Run(run func(token string)) *MockTokenProvider_ParseAccessToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTokenProvider_ParseAccessToken_Call) Return(uUID uuid.UUID, err error) *MockTokenProvider_ParseAccessToken_Call {
	_c.Call.Return(uUID, err)
	return _c
}

func (_c *MockTokenProvider_ParseAccessToken_Call) RunAndReturn(run func(token string) (uuid.UUID, error)) *MockTokenProvider_ParseAccessToken_Call {
	_c.Call.Return(run)
	return _c
}

// ParseRefreshToken provides a mock function for the type MockTokenProvider
func (_mock *MockTokenProvider) ParseRefreshToken(token string) (uuid.UUID, uuid.UUID, error) {
	ret := _mock.Called(token)

	if len(ret) == 0 {
		panic("no return value specified for ParseRefreshToken")
	}

	var r0 uuid.UUID
	var r1 uuid.UUID
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(string) (uuid.UUID, uuid.UUID, error)); ok {
		return returnFunc(token)
	}
	if returnFunc, ok := ret.Get(0).(func(string) uuid.UUID); ok {
		r0 = returnFunc(token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) uuid.UUID); ok {
		r1 = returnFunc(token)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(uuid.UUID)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(string) error); ok {
		r2 = returnFunc(token)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockTokenProvider_ParseRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ParseRefreshToken'
type MockTokenProvider_ParseRefreshToken_Call struct {
	*mock.Call
}

// ParseRefreshToken is a helper method to define mock.On call
//   - token string
func (_e *MockTokenProvider_Expecter) ParseRefreshToken(token any) *MockTokenProvider_ParseRefreshToken_Call {
	return &MockTokenProvider_ParseRefreshToken_Call{Call: _e.mock.On("ParseRefreshToken", token)}
}

func (_c *MockTokenProvider_ParseRefreshToken_Call) Run(run func(token string)) *MockTokenProvider_ParseRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTokenProvider_ParseRefreshToken_Call) Return(uUID uuid.UUID, uUID1 uuid.UUID, err error) *MockTokenProvider_ParseRefreshToken_Call {
	_c.Call.Return(uUID, uUID1, err)
	return _c
}

func (_c *MockTokenProvider_ParseRefreshToken_Call) RunAndReturn(run func(token string) (uuid.UUID, uuid.UUID, error)) *MockTokenProvider_ParseRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}
