// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package chats_service

import (
	"context"
	"messenger/internal/core/domain"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockChatsRepository creates a new instance of MockChatsRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockChatsRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockChatsRepository {
	mock := &MockChatsRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockChatsRepository is an autogenerated mock type for the ChatsRepository type
type MockChatsRepository struct {
	mock.Mock
}

type MockChatsRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockChatsRepository) EXPECT() *MockChatsRepository_Expecter {
	return &MockChatsRepository_Expecter{mock: &_m.Mock}
}

// CreateDirect provides a mock function for the type MockChatsRepository
func (_mock *MockChatsRepository) CreateDirect(ctx context.Context, direct domain.DirectChat, participant1 domain.ChatParticipant, participant2 domain.ChatParticipant) error {
	ret := _mock.Called(ctx, direct, participant1, participant2)

	if len(ret) == 0 {
		panic("no return value specified for CreateDirect")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.DirectChat, domain.ChatParticipant, domain.ChatParticipant) error); ok {
		r0 = returnFunc(ctx, direct, participant1, participant2)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockChatsRepository_CreateDirect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateDirect'
type MockChatsRepository_CreateDirect_Call struct {
	*mock.Call
}

// CreateDirect is a helper method to define mock.On call
//   - ctx context.Context
//   - direct domain.DirectChat
//   - participant1 domain.ChatParticipant
//   - participant2 domain.ChatParticipant
func (_e *MockChatsRepository_Expecter) CreateDirect(ctx any, direct any, participant1 any, participant2 any) *MockChatsRepository_CreateDirect_Call {
	return &MockChatsRepository_CreateDirect_Call{Call: _e.mock.On("CreateDirect", ctx, direct, participant1, participant2)}
}

func (_c *MockChatsRepository_CreateDirect_Call) Run(run func(ctx context.Context, direct domain.DirectChat, participant1 domain.ChatParticipant, participant2 domain.ChatParticipant)) *MockChatsRepository_CreateDirect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.DirectChat
		if args[1] != nil {
			arg1 = args[1].(domain.DirectChat)
		}
		var arg2 domain.ChatParticipant
		if args[2] != nil {
			arg2 = args[2].(domain.ChatParticipant)
		}
		var arg3 domain.ChatParticipant
		if args[3] != nil {
			arg3 = args[3].(domain.ChatParticipant)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockChatsRepository_CreateDirect_Call) Return(err error) *MockChatsRepository_CreateDirect_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockChatsRepository_CreateDirect_Call) RunAndReturn(run func(ctx context.Context, direct domain.DirectChat, participant1 domain.ChatParticipant, participant2 domain.ChatParticipant) error) *MockChatsRepository_CreateDirect_Call {
	_c.Call.Return(run)
	return _c
}

// GetDirectByUsers provides a mock function for the type MockChatsRepository
func (_mock *MockChatsRepository) GetDirectByUsers(ctx context.Context, user1ID uuid.UUID, user2ID uuid.UUID) (domain.DirectChat, error) {
	ret := _mock.Called(ctx, user1ID, user2ID)

	if len(ret) == 0 {
		panic("no return value specified for GetDirectByUsers")
	}

	var r0 domain.DirectChat
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (domain.DirectChat, error)); ok {
		return returnFunc(ctx, user1ID, user2ID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) domain.DirectChat); ok {
		r0 = returnFunc(ctx, user1ID, user2ID)
	} else {
		r0 = ret.Get(0).(domain.DirectChat)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, user1ID, user2ID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockChatsRepository_GetDirectByUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDirectByUsers'
type MockChatsRepository_GetDirectByUsers_Call struct {
	*mock.Call
}

// GetDirectByUsers is a helper method to define mock.On call
//   - ctx context.Context
//   - user1ID uuid.UUID
//   - user2ID uuid.UUID
func (_e *MockChatsRepository_Expecter) GetDirectByUsers(ctx any, user1ID any, user2ID any) *MockChatsRepository_GetDirectByUsers_Call {
	return &MockChatsRepository_GetDirectByUsers_Call{Call: _e.mock.On("GetDirectByUsers", ctx, user1ID, user2ID)}
}

func (_c *MockChatsRepository_GetDirectByUsers_Call) Run(run func(ctx context.Context, user1ID uuid.UUID, user2ID uuid.UUID)) *MockChatsRepository_GetDirectByUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockChatsRepository_GetDirectByUsers_Call) Return(directChat domain.DirectChat, err error) *MockChatsRepository_GetDirectByUsers_Call {
	_c.Call.Return(directChat, err)
	return _c
}

func (_c *MockChatsRepository_GetDirectByUsers_Call) RunAndReturn(run func(ctx context.Context, user1ID uuid.UUID, user2ID uuid.UUID) (domain.DirectChat, error)) *MockChatsRepository_GetDirectByUsers_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTXManager creates a new instance of MockTXManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTXManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTXManager {
	mock := &MockTXManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTXManager is an autogenerated mock type for the TXManager type
type MockTXManager struct {
	mock.Mock
}

type MockTXManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTXManager) EXPECT() *MockTXManager_Expecter {
	return &MockTXManager_Expecter{mock: &_m.Mock}
}

// WithinTransaction provides a mock function for the type MockTXManager
func (_mock *MockTXManager) WithinTransaction(ctx context.Context, fn func(ctx context.Context) error) error {
	ret := _mock.Called(ctx, fn)

	if len(ret) == 0 {
		panic("no return value specified for WithinTransaction")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, func(ctx context.Context) error) error); ok {
		r0 = returnFunc(ctx, fn)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTXManager_WithinTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithinTransaction'
type MockTXManager_WithinTransaction_Call struct {
	*mock.Call
}

// WithinTransaction is a helper method to define mock.On call
//   - ctx context.Context
//   - fn func(ctx context.Context) error
func (_e *MockTXManager_Expecter) WithinTransaction(ctx any, fn any) *MockTXManager_WithinTransaction_Call {
	return &MockTXManager_WithinTransaction_Call{Call: _e.mock.On("WithinTransaction", ctx, fn)}
}

func (_c *MockTXManager_WithinTransaction_Call) Run(run func(ctx context.Context, fn func(ctx context.Context) error)) *MockTXManager_WithinTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 func(ctx context.Context) error
		if args[1] != nil {
			arg1 = args[1].(func(ctx context.Context) error)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTXManager_WithinTransaction_Call) Return(err error) *MockTXManager_WithinTransaction_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTXManager_WithinTransaction_Call) RunAndReturn(run func(ctx context.Context, fn func(ctx context.Context) error) error) *MockTXManager_WithinTransaction_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUsersRepository creates a new instance of MockUsersRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUsersRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUsersRepository {
	mock := &MockUsersRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUsersRepository is an autogenerated mock type for the UsersRepository type
type MockUsersRepository struct {
	mock.Mock
}

type MockUsersRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUsersRepository) EXPECT() *MockUsersRepository_Expecter {
	return &MockUsersRepository_Expecter{mock: &_m.Mock}
}

// GetUserForUpdate provides a mock function for the type MockUsersRepository
func (_mock *MockUsersRepository) GetUserForUpdate(ctx context.Context, userID uuid.UUID) (domain.User, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserForUpdate")
	}

	var r0 domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (domain.User, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) domain.User); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Get(0).(domain.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUsersRepository_GetUserForUpdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserForUpdate'
type MockUsersRepository_GetUserForUpdate_Call struct {
	*mock.Call
}

// GetUserForUpdate is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockUsersRepository_Expecter) GetUserForUpdate(ctx any, userID any) *MockUsersRepository_GetUserForUpdate_Call {
	return &MockUsersRepository_GetUserForUpdate_Call{Call: _e.mock.On("GetUserForUpdate", ctx, userID)}
}

func (_c *MockUsersRepository_GetUserForUpdate_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockUsersRepository_GetUserForUpdate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUsersRepository_GetUserForUpdate_Call) Return(user domain.User, err error) *MockUsersRepository_GetUserForUpdate_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUsersRepository_GetUserForUpdate_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) (domain.User, error)) *MockUsersRepository_GetUserForUpdate_Call {
	_c.Call.Return(run)
	return _c
}
