// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package chats_service

import (
	"context"
	"messenger/internal/core/domain"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockChatsRepository creates a new instance of MockChatsRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockChatsRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockChatsRepository {
	mock := &MockChatsRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockChatsRepository is an autogenerated mock type for the ChatsRepository type
type MockChatsRepository struct {
	mock.Mock
}

type MockChatsRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockChatsRepository) EXPECT() *MockChatsRepository_Expecter {
	return &MockChatsRepository_Expecter{mock: &_m.Mock}
}

// CreateDirect provides a mock function for the type MockChatsRepository
func (_mock *MockChatsRepository) CreateDirect(ctx context.Context, chat domain.Chat, user1 uuid.UUID, user2 uuid.UUID) (domain.Chat, error) {
	ret := _mock.Called(ctx, chat, user1, user2)

	if len(ret) == 0 {
		panic("no return value specified for CreateDirect")
	}

	var r0 domain.Chat
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Chat, uuid.UUID, uuid.UUID) (domain.Chat, error)); ok {
		return returnFunc(ctx, chat, user1, user2)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Chat, uuid.UUID, uuid.UUID) domain.Chat); ok {
		r0 = returnFunc(ctx, chat, user1, user2)
	} else {
		r0 = ret.Get(0).(domain.Chat)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.Chat, uuid.UUID, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, chat, user1, user2)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockChatsRepository_CreateDirect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateDirect'
type MockChatsRepository_CreateDirect_Call struct {
	*mock.Call
}

// CreateDirect is a helper method to define mock.On call
//   - ctx context.Context
//   - chat domain.Chat
//   - user1 uuid.UUID
//   - user2 uuid.UUID
func (_e *MockChatsRepository_Expecter) CreateDirect(ctx any, chat any, user1 any, user2 any) *MockChatsRepository_CreateDirect_Call {
	return &MockChatsRepository_CreateDirect_Call{Call: _e.mock.On("CreateDirect", ctx, chat, user1, user2)}
}

func (_c *MockChatsRepository_CreateDirect_Call) Run(run func(ctx context.Context, chat domain.Chat, user1 uuid.UUID, user2 uuid.UUID)) *MockChatsRepository_CreateDirect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Chat
		if args[1] != nil {
			arg1 = args[1].(domain.Chat)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 uuid.UUID
		if args[3] != nil {
			arg3 = args[3].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockChatsRepository_CreateDirect_Call) Return(chat1 domain.Chat, err error) *MockChatsRepository_CreateDirect_Call {
	_c.Call.Return(chat1, err)
	return _c
}

func (_c *MockChatsRepository_CreateDirect_Call) RunAndReturn(run func(ctx context.Context, chat domain.Chat, user1 uuid.UUID, user2 uuid.UUID) (domain.Chat, error)) *MockChatsRepository_CreateDirect_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTXManager creates a new instance of MockTXManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTXManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTXManager {
	mock := &MockTXManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTXManager is an autogenerated mock type for the TXManager type
type MockTXManager struct {
	mock.Mock
}

type MockTXManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTXManager) EXPECT() *MockTXManager_Expecter {
	return &MockTXManager_Expecter{mock: &_m.Mock}
}

// WithinTransaction provides a mock function for the type MockTXManager
func (_mock *MockTXManager) WithinTransaction(ctx context.Context, fn func(ctx context.Context) error) error {
	ret := _mock.Called(ctx, fn)

	if len(ret) == 0 {
		panic("no return value specified for WithinTransaction")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, func(ctx context.Context) error) error); ok {
		r0 = returnFunc(ctx, fn)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTXManager_WithinTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithinTransaction'
type MockTXManager_WithinTransaction_Call struct {
	*mock.Call
}

// WithinTransaction is a helper method to define mock.On call
//   - ctx context.Context
//   - fn func(ctx context.Context) error
func (_e *MockTXManager_Expecter) WithinTransaction(ctx any, fn any) *MockTXManager_WithinTransaction_Call {
	return &MockTXManager_WithinTransaction_Call{Call: _e.mock.On("WithinTransaction", ctx, fn)}
}

func (_c *MockTXManager_WithinTransaction_Call) Run(run func(ctx context.Context, fn func(ctx context.Context) error)) *MockTXManager_WithinTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 func(ctx context.Context) error
		if args[1] != nil {
			arg1 = args[1].(func(ctx context.Context) error)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTXManager_WithinTransaction_Call) Return(err error) *MockTXManager_WithinTransaction_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTXManager_WithinTransaction_Call) RunAndReturn(run func(ctx context.Context, fn func(ctx context.Context) error) error) *MockTXManager_WithinTransaction_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUsersRepostiory creates a new instance of MockUsersRepostiory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUsersRepostiory(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUsersRepostiory {
	mock := &MockUsersRepostiory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUsersRepostiory is an autogenerated mock type for the UsersRepostiory type
type MockUsersRepostiory struct {
	mock.Mock
}

type MockUsersRepostiory_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUsersRepostiory) EXPECT() *MockUsersRepostiory_Expecter {
	return &MockUsersRepostiory_Expecter{mock: &_m.Mock}
}

// GetUser provides a mock function for the type MockUsersRepostiory
func (_mock *MockUsersRepostiory) GetUser(ctx context.Context, userID uuid.UUID) (domain.User, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUser")
	}

	var r0 domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (domain.User, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) domain.User); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Get(0).(domain.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUsersRepostiory_GetUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUser'
type MockUsersRepostiory_GetUser_Call struct {
	*mock.Call
}

// GetUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockUsersRepostiory_Expecter) GetUser(ctx any, userID any) *MockUsersRepostiory_GetUser_Call {
	return &MockUsersRepostiory_GetUser_Call{Call: _e.mock.On("GetUser", ctx, userID)}
}

func (_c *MockUsersRepostiory_GetUser_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockUsersRepostiory_GetUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUsersRepostiory_GetUser_Call) Return(user domain.User, err error) *MockUsersRepostiory_GetUser_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUsersRepostiory_GetUser_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) (domain.User, error)) *MockUsersRepostiory_GetUser_Call {
	_c.Call.Return(run)
	return _c
}
