// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package users_transport_http

import (
	"context"
	"messenger/internal/core/domain"
	"messenger/internal/features/users/service"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockUsersService creates a new instance of MockUsersService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUsersService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUsersService {
	mock := &MockUsersService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUsersService is an autogenerated mock type for the UsersService type
type MockUsersService struct {
	mock.Mock
}

type MockUsersService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUsersService) EXPECT() *MockUsersService_Expecter {
	return &MockUsersService_Expecter{mock: &_m.Mock}
}

// ChangePassword provides a mock function for the type MockUsersService
func (_mock *MockUsersService) ChangePassword(ctx context.Context, id uuid.UUID, old_password string, new_password string) error {
	ret := _mock.Called(ctx, id, old_password, new_password)

	if len(ret) == 0 {
		panic("no return value specified for ChangePassword")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string) error); ok {
		r0 = returnFunc(ctx, id, old_password, new_password)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUsersService_ChangePassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ChangePassword'
type MockUsersService_ChangePassword_Call struct {
	*mock.Call
}

// ChangePassword is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - old_password string
//   - new_password string
func (_e *MockUsersService_Expecter) ChangePassword(ctx any, id any, old_password any, new_password any) *MockUsersService_ChangePassword_Call {
	return &MockUsersService_ChangePassword_Call{Call: _e.mock.On("ChangePassword", ctx, id, old_password, new_password)}
}

func (_c *MockUsersService_ChangePassword_Call) Run(run func(ctx context.Context, id uuid.UUID, old_password string, new_password string)) *MockUsersService_ChangePassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockUsersService_ChangePassword_Call) Return(err error) *MockUsersService_ChangePassword_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUsersService_ChangePassword_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, old_password string, new_password string) error) *MockUsersService_ChangePassword_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteUser provides a mock function for the type MockUsersService
func (_mock *MockUsersService) DeleteUser(ctx context.Context, id uuid.UUID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUsersService_DeleteUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUser'
type MockUsersService_DeleteUser_Call struct {
	*mock.Call
}

// DeleteUser is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockUsersService_Expecter) DeleteUser(ctx any, id any) *MockUsersService_DeleteUser_Call {
	return &MockUsersService_DeleteUser_Call{Call: _e.mock.On("DeleteUser", ctx, id)}
}

func (_c *MockUsersService_DeleteUser_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockUsersService_DeleteUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUsersService_DeleteUser_Call) Return(err error) *MockUsersService_DeleteUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUsersService_DeleteUser_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) error) *MockUsersService_DeleteUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetUser provides a mock function for the type MockUsersService
func (_mock *MockUsersService) GetUser(ctx context.Context, id uuid.UUID) (domain.User, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetUser")
	}

	var r0 domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (domain.User, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) domain.User); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUsersService_GetUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUser'
type MockUsersService_GetUser_Call struct {
	*mock.Call
}

// GetUser is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockUsersService_Expecter) GetUser(ctx any, id any) *MockUsersService_GetUser_Call {
	return &MockUsersService_GetUser_Call{Call: _e.mock.On("GetUser", ctx, id)}
}

func (_c *MockUsersService_GetUser_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockUsersService_GetUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUsersService_GetUser_Call) Return(user domain.User, err error) *MockUsersService_GetUser_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUsersService_GetUser_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (domain.User, error)) *MockUsersService_GetUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetUsers provides a mock function for the type MockUsersService
func (_mock *MockUsersService) GetUsers(ctx context.Context, limit *int, offset *int) ([]domain.User, error) {
	ret := _mock.Called(ctx, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetUsers")
	}

	var r0 []domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *int, *int) ([]domain.User, error)); ok {
		return returnFunc(ctx, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *int, *int) []domain.User); ok {
		r0 = returnFunc(ctx, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *int, *int) error); ok {
		r1 = returnFunc(ctx, limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUsersService_GetUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUsers'
type MockUsersService_GetUsers_Call struct {
	*mock.Call
}

// GetUsers is a helper method to define mock.On call
//   - ctx context.Context
//   - limit *int
//   - offset *int
func (_e *MockUsersService_Expecter) GetUsers(ctx any, limit any, offset any) *MockUsersService_GetUsers_Call {
	return &MockUsersService_GetUsers_Call{Call: _e.mock.On("GetUsers", ctx, limit, offset)}
}

func (_c *MockUsersService_GetUsers_Call) Run(run func(ctx context.Context, limit *int, offset *int)) *MockUsersService_GetUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *int
		if args[1] != nil {
			arg1 = args[1].(*int)
		}
		var arg2 *int
		if args[2] != nil {
			arg2 = args[2].(*int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUsersService_GetUsers_Call) Return(users []domain.User, err error) *MockUsersService_GetUsers_Call {
	_c.Call.Return(users, err)
	return _c
}

func (_c *MockUsersService_GetUsers_Call) RunAndReturn(run func(ctx context.Context, limit *int, offset *int) ([]domain.User, error)) *MockUsersService_GetUsers_Call {
	_c.Call.Return(run)
	return _c
}

// PatchUser provides a mock function for the type MockUsersService
func (_mock *MockUsersService) PatchUser(ctx context.Context, id uuid.UUID, patch users_service.UserPatch) (domain.User, error) {
	ret := _mock.Called(ctx, id, patch)

	if len(ret) == 0 {
		panic("no return value specified for PatchUser")
	}

	var r0 domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, users_service.UserPatch) (domain.User, error)); ok {
		return returnFunc(ctx, id, patch)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, users_service.UserPatch) domain.User); ok {
		r0 = returnFunc(ctx, id, patch)
	} else {
		r0 = ret.Get(0).(domain.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, users_service.UserPatch) error); ok {
		r1 = returnFunc(ctx, id, patch)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUsersService_PatchUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PatchUser'
type MockUsersService_PatchUser_Call struct {
	*mock.Call
}

// PatchUser is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - patch users_service.UserPatch
func (_e *MockUsersService_Expecter) PatchUser(ctx any, id any, patch any) *MockUsersService_PatchUser_Call {
	return &MockUsersService_PatchUser_Call{Call: _e.mock.On("PatchUser", ctx, id, patch)}
}

func (_c *MockUsersService_PatchUser_Call) Run(run func(ctx context.Context, id uuid.UUID, patch users_service.UserPatch)) *MockUsersService_PatchUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 users_service.UserPatch
		if args[2] != nil {
			arg2 = args[2].(users_service.UserPatch)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUsersService_PatchUser_Call) Return(user domain.User, err error) *MockUsersService_PatchUser_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUsersService_PatchUser_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, patch users_service.UserPatch) (domain.User, error)) *MockUsersService_PatchUser_Call {
	_c.Call.Return(run)
	return _c
}
