// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package users_transport_http

import (
	"context"
	"messenger/internal/core/domain"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockUsersService creates a new instance of MockUsersService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUsersService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUsersService {
	mock := &MockUsersService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUsersService is an autogenerated mock type for the UsersService type
type MockUsersService struct {
	mock.Mock
}

type MockUsersService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUsersService) EXPECT() *MockUsersService_Expecter {
	return &MockUsersService_Expecter{mock: &_m.Mock}
}

// GetUser provides a mock function for the type MockUsersService
func (_mock *MockUsersService) GetUser(ctx context.Context, id uuid.UUID) (domain.User, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetUser")
	}

	var r0 domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (domain.User, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) domain.User); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUsersService_GetUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUser'
type MockUsersService_GetUser_Call struct {
	*mock.Call
}

// GetUser is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockUsersService_Expecter) GetUser(ctx any, id any) *MockUsersService_GetUser_Call {
	return &MockUsersService_GetUser_Call{Call: _e.mock.On("GetUser", ctx, id)}
}

func (_c *MockUsersService_GetUser_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockUsersService_GetUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUsersService_GetUser_Call) Return(user domain.User, err error) *MockUsersService_GetUser_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUsersService_GetUser_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (domain.User, error)) *MockUsersService_GetUser_Call {
	_c.Call.Return(run)
	return _c
}
