// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package messages_service

import (
	"context"
	"messenger/internal/core/domain"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockMessagesRepository creates a new instance of MockMessagesRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMessagesRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMessagesRepository {
	mock := &MockMessagesRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMessagesRepository is an autogenerated mock type for the MessagesRepository type
type MockMessagesRepository struct {
	mock.Mock
}

type MockMessagesRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMessagesRepository) EXPECT() *MockMessagesRepository_Expecter {
	return &MockMessagesRepository_Expecter{mock: &_m.Mock}
}

// AppendMessage provides a mock function for the type MockMessagesRepository
func (_mock *MockMessagesRepository) AppendMessage(ctx context.Context, message domain.Message) error {
	ret := _mock.Called(ctx, message)

	if len(ret) == 0 {
		panic("no return value specified for AppendMessage")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Message) error); ok {
		r0 = returnFunc(ctx, message)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMessagesRepository_AppendMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AppendMessage'
type MockMessagesRepository_AppendMessage_Call struct {
	*mock.Call
}

// AppendMessage is a helper method to define mock.On call
//   - ctx context.Context
//   - message domain.Message
func (_e *MockMessagesRepository_Expecter) AppendMessage(ctx any, message any) *MockMessagesRepository_AppendMessage_Call {
	return &MockMessagesRepository_AppendMessage_Call{Call: _e.mock.On("AppendMessage", ctx, message)}
}

func (_c *MockMessagesRepository_AppendMessage_Call) Run(run func(ctx context.Context, message domain.Message)) *MockMessagesRepository_AppendMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Message
		if args[1] != nil {
			arg1 = args[1].(domain.Message)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMessagesRepository_AppendMessage_Call) Return(err error) *MockMessagesRepository_AppendMessage_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMessagesRepository_AppendMessage_Call) RunAndReturn(run func(ctx context.Context, message domain.Message) error) *MockMessagesRepository_AppendMessage_Call {
	_c.Call.Return(run)
	return _c
}

// CheckParticipant provides a mock function for the type MockMessagesRepository
func (_mock *MockMessagesRepository) CheckParticipant(ctx context.Context, chatID uuid.UUID, participantID uuid.UUID) error {
	ret := _mock.Called(ctx, chatID, participantID)

	if len(ret) == 0 {
		panic("no return value specified for CheckParticipant")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, chatID, participantID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMessagesRepository_CheckParticipant_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckParticipant'
type MockMessagesRepository_CheckParticipant_Call struct {
	*mock.Call
}

// CheckParticipant is a helper method to define mock.On call
//   - ctx context.Context
//   - chatID uuid.UUID
//   - participantID uuid.UUID
func (_e *MockMessagesRepository_Expecter) CheckParticipant(ctx any, chatID any, participantID any) *MockMessagesRepository_CheckParticipant_Call {
	return &MockMessagesRepository_CheckParticipant_Call{Call: _e.mock.On("CheckParticipant", ctx, chatID, participantID)}
}

func (_c *MockMessagesRepository_CheckParticipant_Call) Run(run func(ctx context.Context, chatID uuid.UUID, participantID uuid.UUID)) *MockMessagesRepository_CheckParticipant_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockMessagesRepository_CheckParticipant_Call) Return(err error) *MockMessagesRepository_CheckParticipant_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMessagesRepository_CheckParticipant_Call) RunAndReturn(run func(ctx context.Context, chatID uuid.UUID, participantID uuid.UUID) error) *MockMessagesRepository_CheckParticipant_Call {
	_c.Call.Return(run)
	return _c
}

// GetMessageByClientID provides a mock function for the type MockMessagesRepository
func (_mock *MockMessagesRepository) GetMessageByClientID(ctx context.Context, senderID uuid.UUID, clientMessageID uuid.UUID) (domain.Message, error) {
	ret := _mock.Called(ctx, senderID, clientMessageID)

	if len(ret) == 0 {
		panic("no return value specified for GetMessageByClientID")
	}

	var r0 domain.Message
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (domain.Message, error)); ok {
		return returnFunc(ctx, senderID, clientMessageID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) domain.Message); ok {
		r0 = returnFunc(ctx, senderID, clientMessageID)
	} else {
		r0 = ret.Get(0).(domain.Message)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, senderID, clientMessageID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMessagesRepository_GetMessageByClientID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMessageByClientID'
type MockMessagesRepository_GetMessageByClientID_Call struct {
	*mock.Call
}

// GetMessageByClientID is a helper method to define mock.On call
//   - ctx context.Context
//   - senderID uuid.UUID
//   - clientMessageID uuid.UUID
func (_e *MockMessagesRepository_Expecter) GetMessageByClientID(ctx any, senderID any, clientMessageID any) *MockMessagesRepository_GetMessageByClientID_Call {
	return &MockMessagesRepository_GetMessageByClientID_Call{Call: _e.mock.On("GetMessageByClientID", ctx, senderID, clientMessageID)}
}

func (_c *MockMessagesRepository_GetMessageByClientID_Call) Run(run func(ctx context.Context, senderID uuid.UUID, clientMessageID uuid.UUID)) *MockMessagesRepository_GetMessageByClientID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockMessagesRepository_GetMessageByClientID_Call) Return(message domain.Message, err error) *MockMessagesRepository_GetMessageByClientID_Call {
	_c.Call.Return(message, err)
	return _c
}

func (_c *MockMessagesRepository_GetMessageByClientID_Call) RunAndReturn(run func(ctx context.Context, senderID uuid.UUID, clientMessageID uuid.UUID) (domain.Message, error)) *MockMessagesRepository_GetMessageByClientID_Call {
	_c.Call.Return(run)
	return _c
}

// GetMessages provides a mock function for the type MockMessagesRepository
func (_mock *MockMessagesRepository) GetMessages(ctx context.Context, chatID uuid.UUID, before *MessageCursor, limit int) ([]domain.Message, error) {
	ret := _mock.Called(ctx, chatID, before, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetMessages")
	}

	var r0 []domain.Message
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, *MessageCursor, int) ([]domain.Message, error)); ok {
		return returnFunc(ctx, chatID, before, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, *MessageCursor, int) []domain.Message); ok {
		r0 = returnFunc(ctx, chatID, before, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Message)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, *MessageCursor, int) error); ok {
		r1 = returnFunc(ctx, chatID, before, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMessagesRepository_GetMessages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMessages'
type MockMessagesRepository_GetMessages_Call struct {
	*mock.Call
}

// GetMessages is a helper method to define mock.On call
//   - ctx context.Context
//   - chatID uuid.UUID
//   - before *MessageCursor
//   - limit int
func (_e *MockMessagesRepository_Expecter) GetMessages(ctx any, chatID any, before any, limit any) *MockMessagesRepository_GetMessages_Call {
	return &MockMessagesRepository_GetMessages_Call{Call: _e.mock.On("GetMessages", ctx, chatID, before, limit)}
}

func (_c *MockMessagesRepository_GetMessages_Call) Run(run func(ctx context.Context, chatID uuid.UUID, before *MessageCursor, limit int)) *MockMessagesRepository_GetMessages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 *MessageCursor
		if args[2] != nil {
			arg2 = args[2].(*MessageCursor)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockMessagesRepository_GetMessages_Call) Return(messages []domain.Message, err error) *MockMessagesRepository_GetMessages_Call {
	_c.Call.Return(messages, err)
	return _c
}

func (_c *MockMessagesRepository_GetMessages_Call) RunAndReturn(run func(ctx context.Context, chatID uuid.UUID, before *MessageCursor, limit int) ([]domain.Message, error)) *MockMessagesRepository_GetMessages_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockChatsRepository creates a new instance of MockChatsRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockChatsRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockChatsRepository {
	mock := &MockChatsRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockChatsRepository is an autogenerated mock type for the ChatsRepository type
type MockChatsRepository struct {
	mock.Mock
}

type MockChatsRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockChatsRepository) EXPECT() *MockChatsRepository_Expecter {
	return &MockChatsRepository_Expecter{mock: &_m.Mock}
}

// GetChatForUpdate provides a mock function for the type MockChatsRepository
func (_mock *MockChatsRepository) GetChatForUpdate(ctx context.Context, chatID uuid.UUID) (domain.Chat, error) {
	ret := _mock.Called(ctx, chatID)

	if len(ret) == 0 {
		panic("no return value specified for GetChatForUpdate")
	}

	var r0 domain.Chat
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (domain.Chat, error)); ok {
		return returnFunc(ctx, chatID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) domain.Chat); ok {
		r0 = returnFunc(ctx, chatID)
	} else {
		r0 = ret.Get(0).(domain.Chat)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, chatID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockChatsRepository_GetChatForUpdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetChatForUpdate'
type MockChatsRepository_GetChatForUpdate_Call struct {
	*mock.Call
}

// GetChatForUpdate is a helper method to define mock.On call
//   - ctx context.Context
//   - chatID uuid.UUID
func (_e *MockChatsRepository_Expecter) GetChatForUpdate(ctx any, chatID any) *MockChatsRepository_GetChatForUpdate_Call {
	return &MockChatsRepository_GetChatForUpdate_Call{Call: _e.mock.On("GetChatForUpdate", ctx, chatID)}
}

func (_c *MockChatsRepository_GetChatForUpdate_Call) Run(run func(ctx context.Context, chatID uuid.UUID)) *MockChatsRepository_GetChatForUpdate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockChatsRepository_GetChatForUpdate_Call) Return(chat domain.Chat, err error) *MockChatsRepository_GetChatForUpdate_Call {
	_c.Call.Return(chat, err)
	return _c
}

func (_c *MockChatsRepository_GetChatForUpdate_Call) RunAndReturn(run func(ctx context.Context, chatID uuid.UUID) (domain.Chat, error)) *MockChatsRepository_GetChatForUpdate_Call {
	_c.Call.Return(run)
	return _c
}

// GetDirectMessageState provides a mock function for the type MockChatsRepository
func (_mock *MockChatsRepository) GetDirectMessageState(ctx context.Context, chatID uuid.UUID) (DirectMessageState, error) {
	ret := _mock.Called(ctx, chatID)

	if len(ret) == 0 {
		panic("no return value specified for GetDirectMessageState")
	}

	var r0 DirectMessageState
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (DirectMessageState, error)); ok {
		return returnFunc(ctx, chatID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) DirectMessageState); ok {
		r0 = returnFunc(ctx, chatID)
	} else {
		r0 = ret.Get(0).(DirectMessageState)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, chatID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockChatsRepository_GetDirectMessageState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDirectMessageState'
type MockChatsRepository_GetDirectMessageState_Call struct {
	*mock.Call
}

// GetDirectMessageState is a helper method to define mock.On call
//   - ctx context.Context
//   - chatID uuid.UUID
func (_e *MockChatsRepository_Expecter) GetDirectMessageState(ctx any, chatID any) *MockChatsRepository_GetDirectMessageState_Call {
	return &MockChatsRepository_GetDirectMessageState_Call{Call: _e.mock.On("GetDirectMessageState", ctx, chatID)}
}

func (_c *MockChatsRepository_GetDirectMessageState_Call) Run(run func(ctx context.Context, chatID uuid.UUID)) *MockChatsRepository_GetDirectMessageState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockChatsRepository_GetDirectMessageState_Call) Return(directMessageState DirectMessageState, err error) *MockChatsRepository_GetDirectMessageState_Call {
	_c.Call.Return(directMessageState, err)
	return _c
}

func (_c *MockChatsRepository_GetDirectMessageState_Call) RunAndReturn(run func(ctx context.Context, chatID uuid.UUID) (DirectMessageState, error)) *MockChatsRepository_GetDirectMessageState_Call {
	_c.Call.Return(run)
	return _c
}

// GetGroupSenderState provides a mock function for the type MockChatsRepository
func (_mock *MockChatsRepository) GetGroupSenderState(ctx context.Context, chatID uuid.UUID, senderID uuid.UUID) (AccountState, error) {
	ret := _mock.Called(ctx, chatID, senderID)

	if len(ret) == 0 {
		panic("no return value specified for GetGroupSenderState")
	}

	var r0 AccountState
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (AccountState, error)); ok {
		return returnFunc(ctx, chatID, senderID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) AccountState); ok {
		r0 = returnFunc(ctx, chatID, senderID)
	} else {
		r0 = ret.Get(0).(AccountState)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, chatID, senderID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockChatsRepository_GetGroupSenderState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGroupSenderState'
type MockChatsRepository_GetGroupSenderState_Call struct {
	*mock.Call
}

// GetGroupSenderState is a helper method to define mock.On call
//   - ctx context.Context
//   - chatID uuid.UUID
//   - senderID uuid.UUID
func (_e *MockChatsRepository_Expecter) GetGroupSenderState(ctx any, chatID any, senderID any) *MockChatsRepository_GetGroupSenderState_Call {
	return &MockChatsRepository_GetGroupSenderState_Call{Call: _e.mock.On("GetGroupSenderState", ctx, chatID, senderID)}
}

func (_c *MockChatsRepository_GetGroupSenderState_Call) Run(run func(ctx context.Context, chatID uuid.UUID, senderID uuid.UUID)) *MockChatsRepository_GetGroupSenderState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockChatsRepository_GetGroupSenderState_Call) Return(accountState AccountState, err error) *MockChatsRepository_GetGroupSenderState_Call {
	_c.Call.Return(accountState, err)
	return _c
}

func (_c *MockChatsRepository_GetGroupSenderState_Call) RunAndReturn(run func(ctx context.Context, chatID uuid.UUID, senderID uuid.UUID) (AccountState, error)) *MockChatsRepository_GetGroupSenderState_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTXManager creates a new instance of MockTXManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTXManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTXManager {
	mock := &MockTXManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTXManager is an autogenerated mock type for the TXManager type
type MockTXManager struct {
	mock.Mock
}

type MockTXManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTXManager) EXPECT() *MockTXManager_Expecter {
	return &MockTXManager_Expecter{mock: &_m.Mock}
}

// WithinTransaction provides a mock function for the type MockTXManager
func (_mock *MockTXManager) WithinTransaction(ctx context.Context, fn func(ctx context.Context) error) error {
	ret := _mock.Called(ctx, fn)

	if len(ret) == 0 {
		panic("no return value specified for WithinTransaction")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, func(ctx context.Context) error) error); ok {
		r0 = returnFunc(ctx, fn)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTXManager_WithinTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithinTransaction'
type MockTXManager_WithinTransaction_Call struct {
	*mock.Call
}

// WithinTransaction is a helper method to define mock.On call
//   - ctx context.Context
//   - fn func(ctx context.Context) error
func (_e *MockTXManager_Expecter) WithinTransaction(ctx any, fn any) *MockTXManager_WithinTransaction_Call {
	return &MockTXManager_WithinTransaction_Call{Call: _e.mock.On("WithinTransaction", ctx, fn)}
}

func (_c *MockTXManager_WithinTransaction_Call) Run(run func(ctx context.Context, fn func(ctx context.Context) error)) *MockTXManager_WithinTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 func(ctx context.Context) error
		if args[1] != nil {
			arg1 = args[1].(func(ctx context.Context) error)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTXManager_WithinTransaction_Call) Return(err error) *MockTXManager_WithinTransaction_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTXManager_WithinTransaction_Call) RunAndReturn(run func(ctx context.Context, fn func(ctx context.Context) error) error) *MockTXManager_WithinTransaction_Call {
	_c.Call.Return(run)
	return _c
}
