// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package users_service

import (
	"context"
	"messenger/internal/core/domain"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockHasher creates a new instance of MockHasher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHasher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHasher {
	mock := &MockHasher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockHasher is an autogenerated mock type for the Hasher type
type MockHasher struct {
	mock.Mock
}

type MockHasher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHasher) EXPECT() *MockHasher_Expecter {
	return &MockHasher_Expecter{mock: &_m.Mock}
}

// Compare provides a mock function for the type MockHasher
func (_mock *MockHasher) Compare(hash string, password string) error {
	ret := _mock.Called(hash, password)

	if len(ret) == 0 {
		panic("no return value specified for Compare")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = returnFunc(hash, password)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockHasher_Compare_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Compare'
type MockHasher_Compare_Call struct {
	*mock.Call
}

// Compare is a helper method to define mock.On call
//   - hash string
//   - password string
func (_e *MockHasher_Expecter) Compare(hash any, password any) *MockHasher_Compare_Call {
	return &MockHasher_Compare_Call{Call: _e.mock.On("Compare", hash, password)}
}

func (_c *MockHasher_Compare_Call) Run(run func(hash string, password string)) *MockHasher_Compare_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockHasher_Compare_Call) Return(err error) *MockHasher_Compare_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockHasher_Compare_Call) RunAndReturn(run func(hash string, password string) error) *MockHasher_Compare_Call {
	_c.Call.Return(run)
	return _c
}

// Hash provides a mock function for the type MockHasher
func (_mock *MockHasher) Hash(password string) (string, error) {
	ret := _mock.Called(password)

	if len(ret) == 0 {
		panic("no return value specified for Hash")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (string, error)); ok {
		return returnFunc(password)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(password)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(password)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHasher_Hash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Hash'
type MockHasher_Hash_Call struct {
	*mock.Call
}

// Hash is a helper method to define mock.On call
//   - password string
func (_e *MockHasher_Expecter) Hash(password any) *MockHasher_Hash_Call {
	return &MockHasher_Hash_Call{Call: _e.mock.On("Hash", password)}
}

func (_c *MockHasher_Hash_Call) Run(run func(password string)) *MockHasher_Hash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockHasher_Hash_Call) Return(s string, err error) *MockHasher_Hash_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockHasher_Hash_Call) RunAndReturn(run func(password string) (string, error)) *MockHasher_Hash_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUsersRepository creates a new instance of MockUsersRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUsersRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUsersRepository {
	mock := &MockUsersRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUsersRepository is an autogenerated mock type for the UsersRepository type
type MockUsersRepository struct {
	mock.Mock
}

type MockUsersRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUsersRepository) EXPECT() *MockUsersRepository_Expecter {
	return &MockUsersRepository_Expecter{mock: &_m.Mock}
}

// ChangePassword provides a mock function for the type MockUsersRepository
func (_mock *MockUsersRepository) ChangePassword(ctx context.Context, id uuid.UUID, newPasswordHash string) error {
	ret := _mock.Called(ctx, id, newPasswordHash)

	if len(ret) == 0 {
		panic("no return value specified for ChangePassword")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) error); ok {
		r0 = returnFunc(ctx, id, newPasswordHash)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUsersRepository_ChangePassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ChangePassword'
type MockUsersRepository_ChangePassword_Call struct {
	*mock.Call
}

// ChangePassword is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - newPasswordHash string
func (_e *MockUsersRepository_Expecter) ChangePassword(ctx any, id any, newPasswordHash any) *MockUsersRepository_ChangePassword_Call {
	return &MockUsersRepository_ChangePassword_Call{Call: _e.mock.On("ChangePassword", ctx, id, newPasswordHash)}
}

func (_c *MockUsersRepository_ChangePassword_Call) Run(run func(ctx context.Context, id uuid.UUID, newPasswordHash string)) *MockUsersRepository_ChangePassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUsersRepository_ChangePassword_Call) Return(err error) *MockUsersRepository_ChangePassword_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUsersRepository_ChangePassword_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, newPasswordHash string) error) *MockUsersRepository_ChangePassword_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteUser provides a mock function for the type MockUsersRepository
func (_mock *MockUsersRepository) DeleteUser(ctx context.Context, id uuid.UUID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUsersRepository_DeleteUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUser'
type MockUsersRepository_DeleteUser_Call struct {
	*mock.Call
}

// DeleteUser is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockUsersRepository_Expecter) DeleteUser(ctx any, id any) *MockUsersRepository_DeleteUser_Call {
	return &MockUsersRepository_DeleteUser_Call{Call: _e.mock.On("DeleteUser", ctx, id)}
}

func (_c *MockUsersRepository_DeleteUser_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockUsersRepository_DeleteUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUsersRepository_DeleteUser_Call) Return(err error) *MockUsersRepository_DeleteUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUsersRepository_DeleteUser_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) error) *MockUsersRepository_DeleteUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetUser provides a mock function for the type MockUsersRepository
func (_mock *MockUsersRepository) GetUser(ctx context.Context, id uuid.UUID) (domain.User, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetUser")
	}

	var r0 domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (domain.User, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) domain.User); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUsersRepository_GetUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUser'
type MockUsersRepository_GetUser_Call struct {
	*mock.Call
}

// GetUser is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockUsersRepository_Expecter) GetUser(ctx any, id any) *MockUsersRepository_GetUser_Call {
	return &MockUsersRepository_GetUser_Call{Call: _e.mock.On("GetUser", ctx, id)}
}

func (_c *MockUsersRepository_GetUser_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockUsersRepository_GetUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUsersRepository_GetUser_Call) Return(user domain.User, err error) *MockUsersRepository_GetUser_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUsersRepository_GetUser_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (domain.User, error)) *MockUsersRepository_GetUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetUsers provides a mock function for the type MockUsersRepository
func (_mock *MockUsersRepository) GetUsers(ctx context.Context, limit *int, offset *int) ([]domain.User, error) {
	ret := _mock.Called(ctx, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetUsers")
	}

	var r0 []domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *int, *int) ([]domain.User, error)); ok {
		return returnFunc(ctx, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *int, *int) []domain.User); ok {
		r0 = returnFunc(ctx, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *int, *int) error); ok {
		r1 = returnFunc(ctx, limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUsersRepository_GetUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUsers'
type MockUsersRepository_GetUsers_Call struct {
	*mock.Call
}

// GetUsers is a helper method to define mock.On call
//   - ctx context.Context
//   - limit *int
//   - offset *int
func (_e *MockUsersRepository_Expecter) GetUsers(ctx any, limit any, offset any) *MockUsersRepository_GetUsers_Call {
	return &MockUsersRepository_GetUsers_Call{Call: _e.mock.On("GetUsers", ctx, limit, offset)}
}

func (_c *MockUsersRepository_GetUsers_Call) Run(run func(ctx context.Context, limit *int, offset *int)) *MockUsersRepository_GetUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *int
		if args[1] != nil {
			arg1 = args[1].(*int)
		}
		var arg2 *int
		if args[2] != nil {
			arg2 = args[2].(*int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUsersRepository_GetUsers_Call) Return(users []domain.User, err error) *MockUsersRepository_GetUsers_Call {
	_c.Call.Return(users, err)
	return _c
}

func (_c *MockUsersRepository_GetUsers_Call) RunAndReturn(run func(ctx context.Context, limit *int, offset *int) ([]domain.User, error)) *MockUsersRepository_GetUsers_Call {
	_c.Call.Return(run)
	return _c
}

// PatchUser provides a mock function for the type MockUsersRepository
func (_mock *MockUsersRepository) PatchUser(ctx context.Context, id uuid.UUID, user domain.User) (domain.User, error) {
	ret := _mock.Called(ctx, id, user)

	if len(ret) == 0 {
		panic("no return value specified for PatchUser")
	}

	var r0 domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, domain.User) (domain.User, error)); ok {
		return returnFunc(ctx, id, user)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, domain.User) domain.User); ok {
		r0 = returnFunc(ctx, id, user)
	} else {
		r0 = ret.Get(0).(domain.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, domain.User) error); ok {
		r1 = returnFunc(ctx, id, user)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUsersRepository_PatchUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PatchUser'
type MockUsersRepository_PatchUser_Call struct {
	*mock.Call
}

// PatchUser is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - user domain.User
func (_e *MockUsersRepository_Expecter) PatchUser(ctx any, id any, user any) *MockUsersRepository_PatchUser_Call {
	return &MockUsersRepository_PatchUser_Call{Call: _e.mock.On("PatchUser", ctx, id, user)}
}

func (_c *MockUsersRepository_PatchUser_Call) Run(run func(ctx context.Context, id uuid.UUID, user domain.User)) *MockUsersRepository_PatchUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 domain.User
		if args[2] != nil {
			arg2 = args[2].(domain.User)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUsersRepository_PatchUser_Call) Return(user1 domain.User, err error) *MockUsersRepository_PatchUser_Call {
	_c.Call.Return(user1, err)
	return _c
}

func (_c *MockUsersRepository_PatchUser_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, user domain.User) (domain.User, error)) *MockUsersRepository_PatchUser_Call {
	_c.Call.Return(run)
	return _c
}
