// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package chats_transport_http

import (
	"context"
	"messenger/internal/core/domain"
	"messenger/internal/features/chats/service"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockChatsService creates a new instance of MockChatsService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockChatsService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockChatsService {
	mock := &MockChatsService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockChatsService is an autogenerated mock type for the ChatsService type
type MockChatsService struct {
	mock.Mock
}

type MockChatsService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockChatsService) EXPECT() *MockChatsService_Expecter {
	return &MockChatsService_Expecter{mock: &_m.Mock}
}

// CreateDirect provides a mock function for the type MockChatsService
func (_mock *MockChatsService) CreateDirect(ctx context.Context, currentUserID uuid.UUID, peerID uuid.UUID) (domain.DirectChat, bool, error) {
	ret := _mock.Called(ctx, currentUserID, peerID)

	if len(ret) == 0 {
		panic("no return value specified for CreateDirect")
	}

	var r0 domain.DirectChat
	var r1 bool
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (domain.DirectChat, bool, error)); ok {
		return returnFunc(ctx, currentUserID, peerID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) domain.DirectChat); ok {
		r0 = returnFunc(ctx, currentUserID, peerID)
	} else {
		r0 = ret.Get(0).(domain.DirectChat)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) bool); ok {
		r1 = returnFunc(ctx, currentUserID, peerID)
	} else {
		r1 = ret.Get(1).(bool)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r2 = returnFunc(ctx, currentUserID, peerID)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockChatsService_CreateDirect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateDirect'
type MockChatsService_CreateDirect_Call struct {
	*mock.Call
}

// CreateDirect is a helper method to define mock.On call
//   - ctx context.Context
//   - currentUserID uuid.UUID
//   - peerID uuid.UUID
func (_e *MockChatsService_Expecter) CreateDirect(ctx any, currentUserID any, peerID any) *MockChatsService_CreateDirect_Call {
	return &MockChatsService_CreateDirect_Call{Call: _e.mock.On("CreateDirect", ctx, currentUserID, peerID)}
}

func (_c *MockChatsService_CreateDirect_Call) Run(run func(ctx context.Context, currentUserID uuid.UUID, peerID uuid.UUID)) *MockChatsService_CreateDirect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockChatsService_CreateDirect_Call) Return(directChat domain.DirectChat, b bool, err error) *MockChatsService_CreateDirect_Call {
	_c.Call.Return(directChat, b, err)
	return _c
}

func (_c *MockChatsService_CreateDirect_Call) RunAndReturn(run func(ctx context.Context, currentUserID uuid.UUID, peerID uuid.UUID) (domain.DirectChat, bool, error)) *MockChatsService_CreateDirect_Call {
	_c.Call.Return(run)
	return _c
}

// CreateGroup provides a mock function for the type MockChatsService
func (_mock *MockChatsService) CreateGroup(ctx context.Context, creatorID uuid.UUID, command chats_service.CreateGroupCommand) (domain.GroupChat, error) {
	ret := _mock.Called(ctx, creatorID, command)

	if len(ret) == 0 {
		panic("no return value specified for CreateGroup")
	}

	var r0 domain.GroupChat
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, chats_service.CreateGroupCommand) (domain.GroupChat, error)); ok {
		return returnFunc(ctx, creatorID, command)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, chats_service.CreateGroupCommand) domain.GroupChat); ok {
		r0 = returnFunc(ctx, creatorID, command)
	} else {
		r0 = ret.Get(0).(domain.GroupChat)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, chats_service.CreateGroupCommand) error); ok {
		r1 = returnFunc(ctx, creatorID, command)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockChatsService_CreateGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateGroup'
type MockChatsService_CreateGroup_Call struct {
	*mock.Call
}

// CreateGroup is a helper method to define mock.On call
//   - ctx context.Context
//   - creatorID uuid.UUID
//   - command chats_service.CreateGroupCommand
func (_e *MockChatsService_Expecter) CreateGroup(ctx any, creatorID any, command any) *MockChatsService_CreateGroup_Call {
	return &MockChatsService_CreateGroup_Call{Call: _e.mock.On("CreateGroup", ctx, creatorID, command)}
}

func (_c *MockChatsService_CreateGroup_Call) Run(run func(ctx context.Context, creatorID uuid.UUID, command chats_service.CreateGroupCommand)) *MockChatsService_CreateGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 chats_service.CreateGroupCommand
		if args[2] != nil {
			arg2 = args[2].(chats_service.CreateGroupCommand)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockChatsService_CreateGroup_Call) Return(groupChat domain.GroupChat, err error) *MockChatsService_CreateGroup_Call {
	_c.Call.Return(groupChat, err)
	return _c
}

func (_c *MockChatsService_CreateGroup_Call) RunAndReturn(run func(ctx context.Context, creatorID uuid.UUID, command chats_service.CreateGroupCommand) (domain.GroupChat, error)) *MockChatsService_CreateGroup_Call {
	_c.Call.Return(run)
	return _c
}

// ListChats provides a mock function for the type MockChatsService
func (_mock *MockChatsService) ListChats(ctx context.Context, requesterID uuid.UUID, query chats_service.ListChatsQuery) (chats_service.ChatPage, error) {
	ret := _mock.Called(ctx, requesterID, query)

	if len(ret) == 0 {
		panic("no return value specified for ListChats")
	}

	var r0 chats_service.ChatPage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, chats_service.ListChatsQuery) (chats_service.ChatPage, error)); ok {
		return returnFunc(ctx, requesterID, query)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, chats_service.ListChatsQuery) chats_service.ChatPage); ok {
		r0 = returnFunc(ctx, requesterID, query)
	} else {
		r0 = ret.Get(0).(chats_service.ChatPage)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, chats_service.ListChatsQuery) error); ok {
		r1 = returnFunc(ctx, requesterID, query)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockChatsService_ListChats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListChats'
type MockChatsService_ListChats_Call struct {
	*mock.Call
}

// ListChats is a helper method to define mock.On call
//   - ctx context.Context
//   - requesterID uuid.UUID
//   - query chats_service.ListChatsQuery
func (_e *MockChatsService_Expecter) ListChats(ctx any, requesterID any, query any) *MockChatsService_ListChats_Call {
	return &MockChatsService_ListChats_Call{Call: _e.mock.On("ListChats", ctx, requesterID, query)}
}

func (_c *MockChatsService_ListChats_Call) Run(run func(ctx context.Context, requesterID uuid.UUID, query chats_service.ListChatsQuery)) *MockChatsService_ListChats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 chats_service.ListChatsQuery
		if args[2] != nil {
			arg2 = args[2].(chats_service.ListChatsQuery)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockChatsService_ListChats_Call) Return(chatPage chats_service.ChatPage, err error) *MockChatsService_ListChats_Call {
	_c.Call.Return(chatPage, err)
	return _c
}

func (_c *MockChatsService_ListChats_Call) RunAndReturn(run func(ctx context.Context, requesterID uuid.UUID, query chats_service.ListChatsQuery) (chats_service.ChatPage, error)) *MockChatsService_ListChats_Call {
	_c.Call.Return(run)
	return _c
}
