// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package chats_transport_http

import (
	"context"
	"messenger/internal/core/domain"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockChatsService creates a new instance of MockChatsService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockChatsService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockChatsService {
	mock := &MockChatsService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockChatsService is an autogenerated mock type for the ChatsService type
type MockChatsService struct {
	mock.Mock
}

type MockChatsService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockChatsService) EXPECT() *MockChatsService_Expecter {
	return &MockChatsService_Expecter{mock: &_m.Mock}
}

// CreateChat provides a mock function for the type MockChatsService
func (_mock *MockChatsService) CreateChat(ctx context.Context, userID uuid.UUID, chatType string, name *string, ParticipantIDs []uuid.UUID) (domain.Chat, error) {
	ret := _mock.Called(ctx, userID, chatType, name, ParticipantIDs)

	if len(ret) == 0 {
		panic("no return value specified for CreateChat")
	}

	var r0 domain.Chat
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, *string, []uuid.UUID) (domain.Chat, error)); ok {
		return returnFunc(ctx, userID, chatType, name, ParticipantIDs)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, *string, []uuid.UUID) domain.Chat); ok {
		r0 = returnFunc(ctx, userID, chatType, name, ParticipantIDs)
	} else {
		r0 = ret.Get(0).(domain.Chat)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, string, *string, []uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userID, chatType, name, ParticipantIDs)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockChatsService_CreateChat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateChat'
type MockChatsService_CreateChat_Call struct {
	*mock.Call
}

// CreateChat is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - chatType string
//   - name *string
//   - ParticipantIDs []uuid.UUID
func (_e *MockChatsService_Expecter) CreateChat(ctx any, userID any, chatType any, name any, ParticipantIDs any) *MockChatsService_CreateChat_Call {
	return &MockChatsService_CreateChat_Call{Call: _e.mock.On("CreateChat", ctx, userID, chatType, name, ParticipantIDs)}
}

func (_c *MockChatsService_CreateChat_Call) Run(run func(ctx context.Context, userID uuid.UUID, chatType string, name *string, ParticipantIDs []uuid.UUID)) *MockChatsService_CreateChat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 *string
		if args[3] != nil {
			arg3 = args[3].(*string)
		}
		var arg4 []uuid.UUID
		if args[4] != nil {
			arg4 = args[4].([]uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockChatsService_CreateChat_Call) Return(chat domain.Chat, err error) *MockChatsService_CreateChat_Call {
	_c.Call.Return(chat, err)
	return _c
}

func (_c *MockChatsService_CreateChat_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, chatType string, name *string, ParticipantIDs []uuid.UUID) (domain.Chat, error)) *MockChatsService_CreateChat_Call {
	_c.Call.Return(run)
	return _c
}
