// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package messages_transport_http

import (
	"context"
	"messenger/internal/core/domain"
	"messenger/internal/features/messages/service"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockMessagesService creates a new instance of MockMessagesService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMessagesService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMessagesService {
	mock := &MockMessagesService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMessagesService is an autogenerated mock type for the MessagesService type
type MockMessagesService struct {
	mock.Mock
}

type MockMessagesService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMessagesService) EXPECT() *MockMessagesService_Expecter {
	return &MockMessagesService_Expecter{mock: &_m.Mock}
}

// SendMessage provides a mock function for the type MockMessagesService
func (_mock *MockMessagesService) SendMessage(ctx context.Context, senderID uuid.UUID, command messages_service.SendMessageCommand) (domain.Message, bool, error) {
	ret := _mock.Called(ctx, senderID, command)

	if len(ret) == 0 {
		panic("no return value specified for SendMessage")
	}

	var r0 domain.Message
	var r1 bool
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, messages_service.SendMessageCommand) (domain.Message, bool, error)); ok {
		return returnFunc(ctx, senderID, command)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, messages_service.SendMessageCommand) domain.Message); ok {
		r0 = returnFunc(ctx, senderID, command)
	} else {
		r0 = ret.Get(0).(domain.Message)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, messages_service.SendMessageCommand) bool); ok {
		r1 = returnFunc(ctx, senderID, command)
	} else {
		r1 = ret.Get(1).(bool)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, uuid.UUID, messages_service.SendMessageCommand) error); ok {
		r2 = returnFunc(ctx, senderID, command)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockMessagesService_SendMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendMessage'
type MockMessagesService_SendMessage_Call struct {
	*mock.Call
}

// SendMessage is a helper method to define mock.On call
//   - ctx context.Context
//   - senderID uuid.UUID
//   - command messages_service.SendMessageCommand
func (_e *MockMessagesService_Expecter) SendMessage(ctx any, senderID any, command any) *MockMessagesService_SendMessage_Call {
	return &MockMessagesService_SendMessage_Call{Call: _e.mock.On("SendMessage", ctx, senderID, command)}
}

func (_c *MockMessagesService_SendMessage_Call) Run(run func(ctx context.Context, senderID uuid.UUID, command messages_service.SendMessageCommand)) *MockMessagesService_SendMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 messages_service.SendMessageCommand
		if args[2] != nil {
			arg2 = args[2].(messages_service.SendMessageCommand)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockMessagesService_SendMessage_Call) Return(message domain.Message, b bool, err error) *MockMessagesService_SendMessage_Call {
	_c.Call.Return(message, b, err)
	return _c
}

func (_c *MockMessagesService_SendMessage_Call) RunAndReturn(run func(ctx context.Context, senderID uuid.UUID, command messages_service.SendMessageCommand) (domain.Message, bool, error)) *MockMessagesService_SendMessage_Call {
	_c.Call.Return(run)
	return _c
}
